server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ems_db
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update